# Validation review — HG2

The reviewing surface for the human gate: read the dossier, interrogate it, then sign (or not) with `factory approve <run> hg2`.

A signature is over artifact hashes — editing the dossier after signing voids the approval.

In [1]:
# parameters
dossier_dir = ""

In [2]:
# Parameters
dossier_dir = "/home/pedraum/Dropbox/Work/Practices/TechTrading/Projects/strategy-factory/runs/20260929-221131-toy-method-validation-run/artifacts"

In [3]:
import json, pathlib
art = pathlib.Path(dossier_dir)
d = json.loads((art / 'dossier.json').read_text())
print((art / 'dossier.md').read_text())

# Validation dossier — DonchianBreakout17

Timeframe 1d, fee 0.001, full range 20210101-20260101.

## Purged walk-forward (OOS)

| fold | test window | trades | return |
|---|---|---|---|
| 1 | 20220702-20221231 | 48 | -12.40% |
| 2 | 20221231-20230701 | 35 | +5.75% |
| 3 | 20230702-20231231 | 35 | +12.65% |
| 4 | 20231231-20240630 | 36 | +3.81% |
| 5 | 20240701-20241230 | 42 | +22.82% |
| 6 | 20241230-20250630 | 42 | -9.07% |
| 7 | 20250701-20251230 | 44 | +12.68% |
| **mean** | | | **+5.18%** (5/7 positive) |

## Cost sweep

| fee/side | trades | total return | mean/trade |
|---|---|---|---|
| 0.0000 | 416 | +99.82% | +4.7971% |
| 0.0005 | 416 | +97.69% | +4.6923% |
| 0.0010 | 416 | +95.56% | +4.5877% |
| 0.0020 | 416 | +91.31% | +4.3787% |
| 0.0030 | 416 | +87.05% | +4.1702% |

## Trade shape (full range)

- max realized hold: **107.0 days** (check against the pre-registered purge)
- best month 2021-03 holds **48%** of total profit (G-conc)

## Deflated Sharpe

- annualized SR **1.02** over 1825 daily obs (skew +3.70, kurt 71.9)
- deflation family 24 trials (ledger total 337) → expected max per-period SR 0.0824
- **DSR = 0.091** — deflated within the comparable-basis family (24 trials, 1d, >=300d); the full ledger holds 337 trials and hyperopt epochs are uncounted, so the true search was wider — treat DSR as an upper bound

## Gates

- PASS `zero_fee_sanity` — total return at zero fees: +99.82%
- PASS `cost_coverage` — coverage 23.99× vs required 3.0×

In [4]:
import pandas as pd
wf = pd.DataFrame(d['walkforward']['folds'])
display(wf)
display(pd.DataFrame(d['cost_sweep']))
pd.DataFrame(d['gates'])[['gate','passed','reason']]

   fold               test  trades  profit_total
0     1  20220702-20221231      48     -0.124043
1     2  20221231-20230701      35      0.057518
2     3  20230702-20231231      35      0.126451
3     4  20231231-20240630      36      0.038058
4     5  20240701-20241230      42      0.228165
5     6  20241230-20250630      42     -0.090710
6     7  20250701-20251230      44      0.126832

      fee  trades  profit_total  mean_per_trade
0  0.0000     416      0.998164        0.047971
1  0.0005     416      0.976893        0.046923
2  0.0010     416      0.955622        0.045877
3  0.0020     416      0.913079        0.043787
4  0.0030     416      0.870536        0.041702

              gate  passed                              reason
0  zero_fee_sanity    True  total return at zero fees: +99.82%
1    cost_coverage    True    coverage 23.99× vs required 3.0×

In [5]:
# tear sheet, if the run produced one
from IPython.display import Image, display
for png in sorted(art.glob('*.png')):
    display(Image(str(png)))